### ISSUE TITLE
Does it need a web browser?

### ISSUE THREAD

**Issue by jasmo2** [mwalsher/actioncable-js#5]
I am using react-native. 
Could it be use on a Cross platform architecture?

**Comment by viniciodeltoro** [comment]
I have the same question. I'm building a nativescript app and right now I'm using [this ](https://github.com/sacketty/nativescript-actioncable)npm package. It works properly on Android but I'm getting a websocket error on iOS. I posted my [issue](http://stackoverflow.com/questions/43175006/getting-websocket-error-code-1006-when-trying-to-connect-to-actioncable-server) on Stackoverflow. I'm planing to change the library so that I can see if I keep getting the same error.

**Comment by rlopzc** [comment]
Yes it does @jasmo2

**Comment by jasmo2** [comment]
I have solve the issue. In the  react-Native side you should connect manually and rails will connect automatically

**Comment by jasmo2** [comment]
This is how I have implement the websockets in react-native
```
const WebSockets = (callback) => {
  const ws = new WebSocket(`${URL}/cable`); //eslint-disable-line

  ws.onopen = (data) => {
    const i = JSON.stringify({
      "command": "subscribe", "identifier":"{\"channel\":\"MyChannel\"}"
    });
    // send data request
    const response = ws.send(i); //eslint-disable-line
  };

   ws.onmessage = ((message) => {
     const messageStr = JSON.parse(message.data).message;

      if (messageStr && messageStr === 'changed') {
    
        callback();
      }
   });

   ws.onerror = ((error) => {
       console.log(error.message);
   });

   ws.onclose = ((event) => {
       console.log(event.code, event.reason);
   });
 }
```
